
spring:
  application:
    name: example-activiti
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://9228.starseaing.com:3306/activiti_test?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: my9228@starseaing

  activiti:
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    database-schema-update: true

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848

  main:
    allow-bean-definition-overriding: true


server:
  port: 8883
  servlet:
    context-path: /activiti

mybatis-plus:
  # xml\u5730\u5740
  mapper-locations: classpath:mapper/*Mapper.xml
  # \u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  type-aliases-package: com.starseaing.example.activiti.model
  configuration:
    # \u8FD9\u4E2A\u914D\u7F6E\u4F1A\u5C06\u6267\u884C\u7684sql\u6253\u5370\u51FA\u6765\uFF0C\u5728\u5F00\u53D1\u6216\u6D4B\u8BD5\u7684\u65F6\u5019\u53EF\u4EE5\u7528
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.alibaba.nacos.client.naming: error
    com.starseaing.example.activiti.mcubeuser.McubeUserService: debug

