
spring:
  application:
    name: example-form

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://9228.starseaing.com:3306/activiti_test?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: my9228@starseaing

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848

  main:
    allow-bean-definition-overriding: true


server:
  port: 8882
  servlet:
    context-path: /form

mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.starseaing.example.form.model
  configuration:
     # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.alibaba.nacos.client.naming: error

